project_id = "cinerelay"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[studio]
enabled = false

[inbucket]
enabled = false

[storage]
enabled = false

[auth]
enabled = false

[functions.youtube-websub]
verify_jwt = false

[functions.youtube-subscription-admin]
verify_jwt = false

[functions.youtube-enrichment-worker]
verify_jwt = false
