begin;

create table if not exists public.connector_subscriptions (
  id uuid primary key default gen_random_uuid(),
  source_identity_id uuid not null references public.source_identities(id) on delete cascade,
  provider text not null,
  hub_url text not null,
  topic_url text not null,
  callback_token_hash text not null check (callback_token_hash ~ '^[0-9a-f]{64}$'),
  generation integer not null default 1 check (generation > 0),
  signature_required boolean not null default true,
  state text not null default 'PENDING' check (state in ('PENDING','ACTIVE','RENEWING','UNSUBSCRIBING','INACTIVE','EXPIRED','DENIED','ERROR')),
  lease_seconds integer check (lease_seconds is null or lease_seconds > 0),
  requested_at timestamptz not null default now(),
  verified_at timestamptz,
  expires_at timestamptz,
  renew_after timestamptz,
  denied_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, source_identity_id)
);

create unique index if not exists connector_subscriptions_callback_uq
  on public.connector_subscriptions (provider, callback_token_hash);
create index if not exists connector_subscriptions_renew_idx
  on public.connector_subscriptions (provider, renew_after)
  where state in ('ACTIVE','RENEWING');

create table if not exists public.youtube_channel_state (
  source_identity_id uuid primary key references public.source_identities(id) on delete cascade,
  channel_id text not null unique check (channel_id ~ '^UC[A-Za-z0-9_-]{22}$'),
  uploads_playlist_id text,
  latest_known_video_id text,
  last_websub_at timestamptz,
  last_enriched_at timestamptz,
  last_fallback_check_at timestamptz,
  consecutive_websub_events integer not null default 0 check (consecutive_websub_events >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.connector_receipts (
  id uuid primary key default gen_random_uuid(),
  provider text not null,
  source_identity_id uuid references public.source_identities(id) on delete set null,
  external_key text not null,
  payload_sha256 text check (payload_sha256 is null or payload_sha256 ~ '^[0-9a-f]{64}$'),
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  status text not null default 'RECEIVED' check (status in ('RECEIVED','QUEUED','PROCESSED','IGNORED','REJECTED','FAILED')),
  error_message text,
  metadata jsonb not null default '{}'::jsonb,
  unique (provider, external_key)
);

create index if not exists connector_receipts_source_received_idx
  on public.connector_receipts (source_identity_id, received_at desc);

create table if not exists public.connector_quota_usage (
  id bigint generated by default as identity primary key,
  provider text not null,
  quota_bucket text not null,
  method text not null,
  units numeric not null check (units >= 0),
  request_count integer not null default 1 check (request_count > 0),
  source_identity_id uuid references public.source_identities(id) on delete set null,
  response_status integer,
  usage_day date not null default ((now() at time zone 'utc')::date),
  occurred_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists connector_quota_usage_day_idx
  on public.connector_quota_usage (provider, quota_bucket, usage_day);

create or replace function public.enqueue_job(
  p_job_type text,
  p_idempotency_key text,
  p_payload jsonb,
  p_priority integer default 100,
  p_run_after timestamptz default now()
)
returns uuid
language plpgsql
as $$
declare
  result_id uuid;
begin
  insert into public.jobs (job_type, idempotency_key, payload, priority, run_after)
  values (p_job_type, p_idempotency_key, coalesce(p_payload, '{}'::jsonb), p_priority, p_run_after)
  on conflict (idempotency_key) do update
    set run_after = least(public.jobs.run_after, excluded.run_after),
        priority = least(public.jobs.priority, excluded.priority)
  returning id into result_id;
  return result_id;
end;
$$;

create trigger connector_subscriptions_set_updated_at
before update on public.connector_subscriptions
for each row execute function public.set_updated_at();

create trigger youtube_channel_state_set_updated_at
before update on public.youtube_channel_state
for each row execute function public.set_updated_at();

alter table public.connector_subscriptions enable row level security;
alter table public.youtube_channel_state enable row level security;
alter table public.connector_receipts enable row level security;
alter table public.connector_quota_usage enable row level security;

comment on table public.connector_subscriptions is 'Lease-based connector subscription state. Secrets are derived from a server-side master secret and are never stored in this table.';
comment on table public.youtube_channel_state is 'YouTube-specific operational state for a registered source identity.';
comment on table public.connector_receipts is 'Idempotent receipt ledger for externally delivered connector events.';
comment on table public.connector_quota_usage is 'Append-only provider quota accounting used for hard budget guards.';

commit;
